version: "3.7"

services:
  jupyter:
   build: .
   container_name: jupyterlab
   ports:
     - 8000:8888
   volumes:
     - ./workbooks:/home/jovyan/work
   command: start-notebook.sh --ServerApp.base_url=/home