version: "3.7"

services:
  jupyter:
    build: .
    container_name: jupyterlab
    command: start-notebook.sh --ServerApp.base_url=/home
    ports:
      - 8888:8888
    volumes:
      - ./workbooks:/home/jovyan/work
